### ISSUE TITLE
New version is fugged

### ISSUE THREAD

**Issue by Lunaversitay** [ATomIK/Automatic-SteamAuth#1]
Examples in the read me aren't valid, I tried reverting back but the whole new version is messed up. Login auth still works though.

![](http://i.lunaversity.xyz/0gvk.png)

and ye i tried steamInfo::username (with the handle too)

**Comment by ATomIK** [comment]
fixed it maybe try now

**Comment by Lunaversitay** [comment]
ya works now thanks commie
